baseURL: "https://hybrid-cloud-patterns.io"
languageCode: "en-us"
title: Hybrid Cloud Patterns
theme: "patternfly"
summaryLength: 20
paginate: 6
params:
  site_logo: /images/hybrid_cloud_patterns.png
security:
  exec:
    allow: ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv: (?i)^(GEM_PATH)$

markup:
  asciidocExt:
    attributes: {allow-uri-read, source-highlighter: rouge, icons: font, sectanchors}
    safeMode: unsafe
  tableOfContents:
    startLevel: 1
    endLevel: 4
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  industry: 'industries'
  product: 'products'
  blog_tag: 'blog_tags'

sectionPagesMenu: main

menu:
  main:
  - identifier: patterns
    name: Patterns
    title: Patterns
    url: /patterns/
    weight: 10
  - identifier: learn
    name: Learn
    title: Learn
    url: /learn/
    weight: 20
  - identifier: contribute
    name: Contribute
    title: Contribute
    url: /contribute/
    weight: 30
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 40
